"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const helper_1 = require("./helper");
const uiElements_1 = require("./uiElements");
const view_1 = require("./view");
const render_1 = require("./render");
const modal_1 = require("./modal");
const renderMessageOnScrollThrottle = (0, helper_1.throttle)(render_1.renderMessageOnScroll, 300);
const showArrowOnScrollThrottle = (0, helper_1.throttle)(helper_1.showArrowOnScroll, 200);
document.addEventListener("DOMContentLoaded", view_1.loadPage);
uiElements_1.BUTTONS.SETTINGS.addEventListener("click", () => modal_1.INIT_MODAL.SETTINGS.open());
uiElements_1.BUTTONS.AUTHORIZATION.addEventListener("click", () => modal_1.INIT_MODAL.AUTHORIZATION.open());
uiElements_1.BUTTONS.CONFIRMATION.addEventListener("click", view_1.codeIsThere);
uiElements_1.BUTTONS.EXIT.addEventListener("click", view_1.signOut);
uiElements_1.FORM.CODE.addEventListener("submit", view_1.getCode);
uiElements_1.FORM.MESSAGE.addEventListener("submit", view_1.sendMessage);
uiElements_1.FORM.LOGIN.addEventListener("submit", view_1.saveToken);
uiElements_1.FORM.CHANGE_NAME.addEventListener("submit", view_1.changeName);
uiElements_1.CHAT.START.addEventListener("click", helper_1.scrollToBottom);
uiElements_1.CHAT.LIST.addEventListener("scroll", renderMessageOnScrollThrottle);
uiElements_1.CHAT.LIST.addEventListener("scroll", showArrowOnScrollThrottle);
